### ISSUE TITLE
Suggesting a more verbose repo name

### ISSUE THREAD

**Issue by navidcy** [21centuryweather/RNS_Sydney_1km#2]
Really minor, but could we rename the repo to something `Land-Atmos-RegionalSydney-1km` or something appropriate?

**Comment by matlipson** [comment]
Could do, but it's a cross-project simulation that includes people from "Land-atmos" "atmos-land" from ModSci, but also "extreme weather" and "weather resources" projects. It's just that I've set it up. Agree we should think about naming structures to keep the github easier to navigate. Open to suggestions/ discussions.

**Comment by navidcy** [comment]
What will the simulations be?

no need to have naming structure guidelines? Just something tad more descriptive will be great I think? up to you?

**Comment by matlipson** [comment]
Worked out how to rename repo. We now use the standard MOSRS/NRI usage of RNS for Regional Nesting Suite. Other similar repositories will follow same structure.
