### ISSUE TITLE
Setting up and organising separate domains/repositories

### ISSUE THREAD

**Issue by andrewbrown31** [21centuryweather/RNS_Sydney_1km#3]
Hey all, I was just talking with Yi Huang about using this modelling framework to set up some separate domains centred on Cape Kennaook/Grim. We might set up a new repository as a starting point, and then try and follow your ancillary-generation steps @matlipson.

I'm also wondering if we could start to organise modelling repositories in a GitHub project board?

**Comment by matlipson** [comment]
I haven't used GitHub project boards, but happy to try.

I suggest you checkout (not copy) u-dl705. Then you just need to make your own optional file in the opt/ folder, like I've [done here](https://code.metoffice.gov.uk/trac/roses-u/browser/d/l/7/0/5/trunk/opt/rose-suite-SY_1km.conf).

You then run it with the name of the opt file, e.g. `rose suite-run -O SY_1km`

Then we can copy that optional file back into this suite, and keep all domains together. I can give you write access to push changes for that suite if necessary.

You may also find the [domain plotting code handy](https://github.com/21centuryweather/Sydney_1km/blob/main/plotting_code/plot_domains.py), using analysis3.

**Comment by matlipson** [comment]
Oh, also @navidcy asked for a more verbose github repo name than this one (I don't think I'm able to change this though). 

Something to guide people as to the model/setup. Perhaps RAL (for regional atmosphere land) or RNS (for regional nesting suite) at the start? I would find "regional-atmosphere-land_Sydney_1km" or similar a bit too verbose for a repo directory though.

**Comment by andrewbrown31** [comment]
Okay maybe we can go with `RNS_DomainName_InnerResolution` for other repositories in general? This is related to #2

**Comment by Rush74** [comment]
If setting up a new domain, I've copied Scott Wales' tools to visual the domain boundaries into a notebook here:

https://github.com/21centuryweather/UM_configuration_tools/blob/main/UM_plot_domain.ipynb

I've also created a notebook which plots all the qrparm ancillary files for every domain and will check for any 'nan' values that are on land points.

https://github.com/21centuryweather/UM_configuration_tools/blob/main/Check_UM_ancillaries.ipynb

Some that logic might come in handy which you are trying new domains.

**Comment by andrewbrown31** [comment]
For the other domain we are thinking of running, I've set up a [separate repository](https://github.com/21centuryweather/RNS_CAPE-K_1km). I thought it would be cool to link it to an [RNS project board](https://github.com/orgs/21centuryweather/projects/4/views/1), feel free to also assign Sydney_1km issues if you like. Could be useful if we continue with having several repositories for many different simulations.
