### ISSUE TITLE
RNS ostia failure using BARRA-R2 initial conditions

### ISSUE THREAD

**Issue by matlipson** [21centuryweather/RNS_Sydney_1km#4]
If I try to use BARRA-R2 land source rather than ERA5-land (i.e. NCI_HRES_ECCB in driving model setup), I get an error in the new OSTIA-enabled RNS, see below.

It seems to have something to do with the largest EC domain, which for me is 340 x 420.  I know this is different to your original 470x470, just wondered if Chermelle had any ideas as to what might be causing this? (for some reason I can't tag you here).

<img width="948" alt="Screenshot 2024-12-20 at 10 44 30 AM" src="https://github.com/user-attachments/assets/5f6cc4ef-b823-4fab-8094-4386580f43a4" />

**Comment by engelca** [comment]
Have you updated the spatial resolution of the first nest from 0.1, 0.1 to 0.11, 0.11 and changed the overall pixel to be from the BARRA-R2 latitude/longitude set?

**Comment by matlipson** [comment]
No! Both excellent points, thank you.

**Comment by matlipson** [comment]
I confirm BARRA-R2 ICS works with updated ancils, closing.
